### ISSUE TITLE
Error while preprocessing and alignment

### ISSUE THREAD

**Issue by tarak77** [tanlongzhi/dip-c#11]
Hi Tan,

Initially I was using hickit for my mESC diploid cell data and got results but the 3D models were a bit non contiguous, since I was using a high resolution for less contacts (https://github.com/lh3/hickit/issues/5#issuecomment-421670815) , but now was trying to use dip-c for the same data. 

Since I don't have META reads, I skip the `lianti trim -` option in the command below and get an error:
```
(py2) wg-dhcp174d163d001:seqtk tarakshisode$ ./seqtk mergepe ../nuc_processing-master/data/lane4559_AGGCAGAA_CTCTCTAT_1CDX1-25_L001_R1.fq.gz ../nuc_processing-master/data/lane4559_AGGCAGAA_CTCTCTAT_1CDX1-25_L001_R4.fq.gz | bwa mem -Cp ../GRCm38.p6.genome.fa - | samtools view -uS | sambamba sort -o ../dip-c/1CDX1-25.new/aln.bam /dev/stdin
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[M::process] read 66226 sequences (10000126 bp)...
[M::process] 0 single-end sequences; 66226 paired-end sequences
[M::process] read 66226 sequences (10000126 bp)...
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (474, 15653, 432, 453)
[M::mem_pestat] analyzing insert size distribution for orientation FF...
[M::mem_pestat] (25, 50, 75) percentile: (1403, 3030, 5782)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 14540)
[M::mem_pestat] mean and std.dev: (3759.79, 2708.84)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 18919)
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (173, 241, 328)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 638)
[M::mem_pestat] mean and std.dev: (250.96, 110.76)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 793)
[M::mem_pestat] analyzing insert size distribution for orientation RF...
[M::mem_pestat] (25, 50, 75) percentile: (1496, 3001, 5646)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 13946)
[M::mem_pestat] mean and std.dev: (3699.66, 2695.92)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 18096)
[M::mem_pestat] analyzing insert size distribution for orientation RR...
[M::mem_pestat] (25, 50, 75) percentile: (1581, 3400, 5536)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 13446)
[M::mem_pestat] mean and std.dev: (3817.76, 2657.10)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 17401)
[M::mem_pestat] skip orientation FF
[M::mem_pestat] skip orientation RF
[M::mem_pestat] skip orientation RR
[M::mem_process_seqs] Processed 66226 reads in 75.280 CPU sec, 75.835 real sec
[M::process] 0 single-end sequences; 66226 paired-end sequences
[E::sam_parse1] unrecognized type :
[W::sam_read1] Parse error at line 141
[main_samview] truncated file.
```
But since I had a `aln.sam` file from hickit, I convert it to `aln.bam ` and use the command for identifying genomic contacts which again leads to an error:
```
(py2) wg-dhcp174d163d001:dip-c tarakshisode$ ./dip-c seg -v ../hickit/cast_129.phased_SNP.tsv.gz ./1CDX1-25.new/aln.bam | gzip -c > ./1CDX1-25.new/phased.seg.gz
[M::seg] pass 1: read 100000 alignments, last at chr1:29284440; added 16587 candidate reads
[M::seg] pass 1: read 200000 alignments, last at chr9:9941957; added 33426 candidate reads
[M::seg] pass 1: read 300000 alignments, last at chr4:13580230; added 50199 candidate reads
[M::seg] pass 1: read 400000 alignments, last at chr8:32597482; added 66488 candidate reads
[M::seg] pass 1: read 500000 alignments, last at chr11:21056174; added 82555 candidate reads
[M::seg] pass 1: read 600000 alignments, last at chr13:85023688; added 98829 candidate reads
[M::seg] pass 1: read 700000 alignments, last at chrX:120371153; added 115411 candidate reads
[M::seg] pass 1: read 800000 alignments, last at chr17:83341705; added 132316 candidate reads
[M::seg] pass 1: read 900000 alignments, last at chr7:122738108; added 147914 candidate reads
[M::seg] pass 1: read 1000000 alignments, last at chr9:117142127; added 163607 candidate reads
[M::seg] pass 1: read 1100000 alignments, last at chr8:89389020; added 180175 candidate reads
[M::seg] pass 1: read 1200000 alignments, last at chr2:136069232; added 195341 candidate reads
[M::seg] pass 1 done: read 1234782 alignments; added 200594 candidate reads (16.25% of alignments)
[M::seg] pass 2: read 100000 alignments, last at chr1:29284440
[M::seg] pass 2: read 200000 alignments, last at chr9:9941957
[M::seg] pass 2: read 300000 alignments, last at chr4:13580230
[M::seg] pass 2: read 400000 alignments, last at chr8:32597482
[M::seg] pass 2: read 500000 alignments, last at chr11:21056174
[M::seg] pass 2: read 600000 alignments, last at chr13:85023688
[M::seg] pass 2: read 700000 alignments, last at chrX:120371153
[M::seg] pass 2: read 800000 alignments, last at chr17:83341705
[M::seg] pass 2: read 900000 alignments, last at chr7:122738108
[M::seg] pass 2: read 1000000 alignments, last at chr9:117142127
[M::seg] pass 2: read 1100000 alignments, last at chr8:89389020
[M::seg] pass 2: read 1200000 alignments, last at chr2:136069232
[M::seg] pass 2: cleaning 200594 candidate reads
[M::seg] pass 2 done: read 1234782 alignments; kept 151510 candidate reads (12.27% of alignments)
Traceback (most recent call last):
  File "./dip-c", line 122, in <module>
    main()
  File "./dip-c", line 40, in main
    return_value = seg.seg(sys.argv[1:])
  File "/Users/tarakshisode/dip-c/seg.py", line 129, in seg
    for pileup_column in bam_file.pileup(snp_chr, snp_locus - 1, snp_locus):
  File "pysam/libcalignmentfile.pyx", line 1327, in pysam.libcalignmentfile.AlignmentFile.pileup
ValueError: no index available for pileup
```

Am I doing something wrong??

**Comment by tanlongzhi** [comment]
Hi Tarak,

I'm not sure why you're having problem with mapping. Can you attach a small subset of your input FASTQ files that can reproduce the problem?

Regarding your second part, to use raw SAM output from BWA (for example, the hickit SAM files), you need to convert it to a *sorted* BAM file. The code to sort will be something like:

```sh
samtools view -uS aln.sam.gz | sambamba sort /dev/stdin -o aln.bam
```

**Comment by tarak77** [comment]
Sure, here are the input FASTQ files: 
lane4559_AGGCAGAA_CTCTCTAT_1CDX1-25_L001_R1.fq.gz
lane4559_AGGCAGAA_CTCTCTAT_1CDX1-25_L001_R4.fq.gz

**Comment by tarak77** [comment]
Sure, here are the subset of FASTQ files
[lane4559_AGGCAGAA_CTCTCTAT_1CDX1-25_L001_R1.new.fq.gz](https://github.com/tanlongzhi/dip-c/files/2407301/lane4559_AGGCAGAA_CTCTCTAT_1CDX1-25_L001_R1.new.fq.gz)
[lane4559_AGGCAGAA_CTCTCTAT_1CDX1-25_L001_R4.new.fq.gz](https://github.com/tanlongzhi/dip-c/files/2407302/lane4559_AGGCAGAA_CTCTCTAT_1CDX1-25_L001_R4.new.fq.gz)

**Comment by tanlongzhi** [comment]
Thank you for attaching the files. Please use `bwa mem -p` instead of `bwa mem -Cp`. The `-C` option of BWA ends up carrying over the Illumina barcode tags, ill-formatted for `samtools view`.

**Comment by tarak77** [comment]
Oh okay, anyways I went with the sam to bam option. Getting the phased.seg files is taking a while though.

**Comment by tanlongzhi** [comment]
I'm not sure why your `aln.bam` (and consequently, `phased.seg.gz`) is so small. Mapping may have crashed somewhere early.

On the other hand, the reason `dip-c reg` crashed here is because the preset should be set to mouse (`-p mf`) instead of human (`-p hf`).

**Comment by tarak77** [comment]
got it, thanks
